### ISSUE TITLE
Add an option to use field_name as default value when missing 

### ISSUE THREAD

**Issue by erajkovic** [apiaryio/dredd#1019]
#### Describe your problem

Why I understand that the origin of the tool was in API first, to make Dredd more useful when used after the fact, it would be nice to add an option to the CLI that would enable to default required URI parameters which are not defined in the swagger document.

A simple rule could be to use the parameter's name as value.

Here is a sample error message I am getting a lot with our set of APIs:
```
dredd ./integ-um.json http://localhost:8080 --names --dry-run
...
error: Compilation error in file './integ-um.json': Required URI parameter 'id' has no example or default value. (Process/Tasks > /ic/api/process/v1/tasks/{id}/form/live > Update a Form)
warn: Compilation warning in file './integ-um.json': Ambiguous URI parameter in template: /ic/api/process/v1/tasks/{id}/form/live
No example value for required parameter in API description document: id (Process/Tasks > /ic/api/process/v1/tasks/{id}/form/live > Update a Form)
error: Compilation error in file './integ-um.json': Required URI parameter 'id' has no example or default value. (Process/Tasks > /ic/api/process/v1/tasks/{id}/form/live > Update a Form)
warn: Compilation warning in file './integ-um.json': Ambiguous URI parameter in template: /ic/api/process/v1/tasks/{id}/form/live
No example value for required parameter in API description document: id (Process/Tasks > /ic/api/process/v1/tasks/{id}/form/live > Update a Form)
error: Compilation error in file './integ-um.json': Required URI parameter 'id' has no example or default value. (Process/Tasks > /ic/api/process/v1/tasks/{id}/form/live > Update a Form)
warn: Compilation warning in file './integ-um.json': Ambiguous URI parameter in template: /ic/api/process/v1/tasks/{id}/form/live
No example value for required parameter in API description document: id (Process/Tasks > /ic/api/process/v1/tasks/{id}/form/live > Update a Form)
...
```
The duplicate message is because we have get/post/delete operations on this URI

#### What command line options do you use?

```
$ dredd ... --generates-default-value
```
or any other way to do it would work as well.

#### What's your `dredd --version` output?

```
dredd v5.1.6
```

**Comment by erajkovic** [comment]
Wondering if it should not even be the default behavior so that you get cranking faster.

**Comment by honzajavorek** [comment]
This is already the case (or at least should be) in the Apiary Console, where the missing values get inferred from the parameter names. It never occurred to me Dredd could do the same. I think it's actually a pretty good idea!

I'm just wondering whether this would be responsibility of the Fury adapters (since the Swagger adapter already infers whole body examples in case they're missing) or of the API Elements tooling (Dredd). What do you think, @apiaryio/adt?

**Comment by pksunkara** [comment]
No, this should be left to the tools that are consuming the API elements on how to interpret.

**Comment by honzajavorek** [comment]
Things, which I'm not completely sure about:

- `Required URI parameter 'id' has no example or default value` means there is any kind of value missing in the original document. Dredd could use the parameter name by default, but is it useful? E.g. in this particular case, is it useful for Dredd to go with `id` if the value should be numerical? The test will probably fail again, but the user gets confused on why it fails.
- `Ambiguous URI parameter in template` means there is no spec about the parameter in the API description document. Dredd doesn't know anything about it, nor does the user of the API. Looks like a genuine error for testing to me. Yes, it doesn't error when generating docs in Apiary, because it's possible to generate incomplete docs. Again, Dredd could fill the gap with `id`, but isn't it just postponing the failure one step further and obfuscating the root cause? Because if the service awaits anything else than string, this is going to fail anyway, as in the previous case.

Opinions?

**Comment by erajkovic** [comment]
For my use case, I would go with a default value and provide a sensible default for the type we know about, like integer or date-time. Right now, I am facing a simple issue where Dredd can't be use - full stop. 
You could go with another approach and define the default value for parameter in a config file, so that I can work around this with some extra work.
Also, in my experience, having the ability to execute real tests is a dangerous proposition, so I would not be too concerned about having default that are most likely to get you 404 - it's better than getting a 204 once.

**Comment by honzajavorek** [comment]
Dredd is designed to verify whether the API correctly follows the API description in the description document, in the _development phase_ of the API. Running Dredd gives you yes/no answer to the question whether the API can go to production.

The testing step is meant to be done before deployment, so the target server is supposed to be a development version of the application, either on your local machine, or your continuous integration server, possibly with some fixtures and without any risk of causing harm by non-idempotent requests.

The intention is usually to get the API description document into shape when it describes real requests and then to verify whether the API responds correctly to such requests. Using Dredd to check production-deployed APIs isn't really a common use case, I believe. It could probably make some sense as a smoke test, with [Dredd hooks](http://dredd.org/en/latest/hooks.html) limiting the testing only to specific endpoints or methods... 🤔 

If I read you correctly, your use case is more about getting Dredd running without touching the original API description document, possibly testing just a few endpoints and getting "expected" errors when the tests could modify the server state (`POST`, `DELETE`, etc.). With unspecified parameters defaulting to dummy values, also getting 404 errors on `GET` endpoints. But how is it useful? What questions can be answered by such tests?

The errors we're discussing here is a way for Dredd to say: "I don't have enough information to perform useful tests." I guess one option would be to skip such endpoints with a warning, and to test the rest, instead of halting at once.

After initial cheer, I'm now doubting whether default dummy parameter values are something aligned with the Dredd's original idea.

**Comment by erajkovic** [comment]
Maybe I should not be using Dredd to validate the work as we are definitely not ready for Design first with the set of Swagger documents I am dealing with - now processing ~4300 Swagger documents on a given batch job.

**Comment by honzajavorek** [comment]
@erajkovic, I'm glad you opened the broader topic of testing production by this issue. I created this "meta" issue to discuss how Dredd should approach that: https://github.com/apiaryio/dredd/issues/1103
