### ISSUE TITLE
There is a path parameter and I don't want to give it a default value in swagger.

### ISSUE THREAD

**Issue by thesageinpilani** [apiaryio/dredd#1034]
There is a Path parameter and I don't want to specify a default value for it. for example,

/path/{pathParameter}/random:

The above pathParameter does require a default value or else the dredd is throwing a compilation error.

error: Error when processing API description.

Can you please tell me, how do i remove this error, since i will be replacing the path parameter in hooks.

**Comment by honzajavorek** [comment]
Would it work for you to specify _example_ value instead of _default_ value? Swagger 2.0 doesn't really support example values for request parameters, but we do: [`x-example`](http://dredd.org/en/latest/how-to-guides.html#example-values-for-request-parameters)

For path parameters, Dredd needs to know what to put into the URL, otherwise it wouldn't be able to test the endpoint. Any value is good enough for this - default or example.

**Comment by thesageinpilani** [comment]
Thanks @honzajavorek . you are great! 😀

**Comment by honzajavorek** [comment]
You're welcome! 🙂
