### ISSUE TITLE
Dredd 5.3.0 uses Lorem Ipsum instead of given example values

### ISSUE THREAD

**Issue by dsommerich** [apiaryio/dredd#1147]
**Describe the bug**

5.3.0 no longer uses the given example for a parameter and instead uses generated Lorem Ipsum.

Bisecting Dredd shows that [this commit](https://github.com/apiaryio/dredd/commit/08b3e8c3d3bba2806a6552debac7f0393a4e6c7f) broke it, but I couldn't figure out how to bisect `dredd-transactions` and get it to run.

**To Reproduce**

```yaml
swagger: '2.0'
info:
  version: '0.0.1'
  title: Dredd Bug

consumes:
- application/json

definitions:
  Foo:
    type: object
    properties:
      a:
        type: string

paths:
  /:
    post:
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Foo'
            example:
              a: qwertyuiop
      responses:
        200:
          description: OK
```

Running `dredd swagger.yaml http://localhost:8080/` with Dredd 5.3.0, this gets posted:

```
method: POST
uri: /
headers:
    Content-Type: application/json
    User-Agent: Dredd/5.3.0 (Linux 4.19.4-arch1-1-ARCH; x64)

body:
{
  "a": "et exercitation dolore sit in"
}
```

**Expected behavior**

Using Dredd 5.2.0, this is posted:

```
request:
method: POST
uri: /
headers:
    Content-Type: application/json
    User-Agent: Dredd/5.2.0 (Linux 4.19.4-arch1-1-ARCH; x64)

body:
{
  "a": "qwertyuiop"
}
```

**What is in your `dredd.yml`?**

I have no `dredd.yml`.

**What's your `dredd --version` output?**

- 5.2.0: `dredd v5.2.0 (Linux 4.19.4-arch1-1-ARCH; x64)`
- 5.3.0: `dredd v5.3.0 (Linux 4.19.4-arch1-1-ARCH; x64)`

**Does `dredd --level=debug` uncover something?**

Nope.

**Can you send us failing test in a Pull Request?**

The provided swagger file should be a good start.

**Comment by kylef** [comment]
I can see why this used to work, due to the implementation details of the Swagger parser. However I don't believe it *should* have worked, because of the semantics of `$ref` replaces the entire object reference object thus discarding the example.

Here's a quote from JSON Schema Draft 4 specification:

> An object schema with a "$ref" property MUST be interpreted as a "$ref" reference. The value of the "$ref" property MUST be a URI Reference. Resolved against the current URI base, it identifies the URI of a schema to use. **All other properties in a "$ref" object MUST be ignored.**

The OpenAPI 2 Specification doesn't show that any other properties are permitted in a 'Reference Object': https://github.com/OAI/OpenAPI-Specification/blob/50c152549263cda0f05608d514ba78546b390d0e/versions/2.0.md#reference-object

You can move the example from the parameter schema into the 'Schema Object' itself:

```diff
@@ -12,6 +12,8 @@ definitions:
     properties:
       a:
         type: string
+    example:
+      a: qwertyuiop

 paths:
   /:
@@ -21,8 +23,6 @@ paths:
           name: body
           schema:
             $ref: '#/definitions/Foo'
-            example:
-              a: qwertyuiop
       responses:
         200:
           description: OK
```

You can also move it directly into the property, this usually helps DRY up examples as every time the property is referenced from anywhere else the example will be used:

```diff
diff --git a/test/fixtures/dredd.yaml b/test/fixtures/dredd.yaml
index bba1075..fda7d84 100644
--- a/test/fixtures/dredd.yaml
+++ b/test/fixtures/dredd.yaml
@@ -12,6 +12,7 @@ definitions:
     properties:
       a:
         type: string
+        example: qwertyuiop

 paths:
   /:
@@ -21,8 +22,6 @@ paths:
           name: body
           schema:
             $ref: '#/definitions/Foo'
-            example:
-              a: qwertyuiop
       responses:
         200:
           description: OK
```

If you do indeed want a separate example specifically for the paramerer, than you can use `allOf`, for example:

```diff
diff --git a/test/fixtures/dredd.yaml b/test/fixtures/dredd.yaml
index bba1075..616bf39 100644
--- a/test/fixtures/dredd.yaml
+++ b/test/fixtures/dredd.yaml
@@ -20,7 +20,8 @@ paths:
         - in: body
           name: body
           schema:
-            $ref: '#/definitions/Foo'
+            allOf:
+              - $ref: '#/definitions/Foo'
             example:
               a: qwertyuiop
       responses:
```

**Comment by dsommerich** [comment]
Thanks, working now with 5.2.0 and 5.3.0 after fixing the Swagger.
