### ISSUE TITLE
API description processing error

### ISSUE THREAD

**Issue by uniquelau** [apiaryio/dredd#1664]
**Describe the bug**
OpenApi 3.0, document is throwing the following error:
When running `> dredd`

> yml:2 (line 2 column 1): YAML Syntax: expected '<document start>', but found <block mapping end>
> error: API description processing error

I have been working with this file for a few days, and have had no problems.
Have reverted the file back to older versions, but the error is still thrown. 
Even if I try and process just the text below, it throws the same error.

***Versions***
dredd v13.0.0

```yml
openapi: 3.0.0
servers:
  - description: Local dev
    url: http://cameraworks.store.webapi/v1
    
info:
  description: Web API for Cameraworks Store application.
  version: "1.0.0"
  title: Cameraworks Store API
  contact:
    email: email@domain.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
```

**Comment by kylef** [comment]
Hi @uniquelau, I've copied your YAML document from above and tried to use it with Dredd and it's behaving (as expected) where I get an error due to missing properties. That check happens after YAML document has been parsed.

What I think could be the case is that there is a unicode non-breaking space or special character in the document at line 2/column 1 which isn't present when you copy the document to the GitHub issue. Could you perhaps check the document in a hex editor and verify? you could also try rewriting line 2 (removing any odd unicode characters) to see if the problem goes away.

```shell
$ dredd dredd1664.yaml http://example.com
error: API description parser error in /Users/kyle/Projects/apiaryio/api-elements.js/dredd1664.yaml:1 (from line 1 column 1 to line 15 column 1): 'OpenAPI Object' is missing required property 'paths'
error: API description processing error
```

**Comment by uniquelau** [comment]
Hmm so strange! 
Double checked for ghost characters, but couldn't find anything.
But re-encoded the file from UTF-8 to ANSI has resolved the issues.
