### ISSUE TITLE
--sorted does not really sorts how it should

### ISSUE THREAD

**Issue by RassaLibre** [apiaryio/dredd#170]
Hi,
just a thing I have noticed. The example on how to use Dredd does not really show how to get rid of the document created with the POST request. I guess that the intention is that after Dredd is done, the database should be in the same state as it was before the testing.

--sorted sorts requests only based on the method but not based on the URL. When I am posting new data, I want to first post root data and then nested like:

	1. POST /universities
	2. POST /universities/42/faculties
	3. POST /universities/42/faculties/43/sections
	
When one wants to delete documents, one needs to do this in the opposite order, otherwise one runs into 404.

	1. DELETE /universities/42/faculties/43/sections/45
	2. DELETE /universities/42/faculties/43
	3. DELETE /universities/42
	
Dredd does not include this kind of sorting and I think it should.

**Comment by RassaLibre** [comment]
Ehm... Is that just a stupid notice oooooor?

**Comment by ecordell** [comment]
Hi, I think I might be able to clear up some of your questions.

> I guess that the intention is that after Dredd is done, the database should be in the same state as it was before the testing.

That's certainly an option but it's not the only way you can do things. For example, you could seed your database so that it's ready for testing, run your api tests, and then reseed your database to get it back to a known state.

>--sorted sorts requests only based on the method but not based on the URL. When I am posting new data, I want to first post root data and then nested like:
>
> 1. POST /universities
> 2. POST /universities/42/faculties
> 3. POST /universities/42/faculties/43/sections

> Dredd does not include this kind of sorting and I think it should.

You're correct that `--sorted` does not take the url into account. Part of the problem with doing that is that the url doesn't actually have to be related to the resources and transitions being manipulated through the api - It would be perfectly valid for an API to not follow the strict hierarchical urls you're using.

It may be that this case is common enough that it would be good to include it in dredd?  But I think it only solves part of the problem - it is likely that even with a more advanced sorting like you're suggesting, there will be order dependencies outside of that sorting (e.g. maybe POST /universities requires that you reference a unique "accreditation" resource that must already exist)

You can however build arbitrary dependency graphs using hookfiles. Here's a quick example based on the requests you mentioned:

```coffeescript
{before, after, transactions} = require 'hooks'

before 'Universities > Faculties > Create Faculty', (transaction, done) ->
   # create a new university (omitted for brevity)
   # store universityId in a variable
   body = JSON.parse transaction.request.body
   body.universityId = universityId
   transaction.request.body = JSON.stringify body
   transaction.request.headers['Content-Length'] = transaction.request.body.length
   done()

after 'Universities > Faculties > Delete Faculty',  (transaction, done) ->
   # delete university created in earlier hook
   done()
```

This can get complicated and unwieldy pretty quickly, but it does allow you to test any workflow you want.  Careful code organization can make things a bit nicer.

**Comment by RassaLibre** [comment]
Hi, thank you for your reply. It gave me some very useful information. You are right that what I am describing can be helpful in some cases but it is not a silver bullet. I have already implemented the sorting in my repo [here](https://github.com/RassaLibre/endpoint-sorter) and I even managed to clone Dredd and extend the sorting function. It is just hard to test because the test for the sorting takes *stdout* and then compares the indexes of each method. It would be super difficult for me to test it based on *stdout* so that is why there is no pull request so far. I do not dare without tests :-) Maybe I will just try something one day and then we will see if it gets accepted or not.

You are right that the problem is not black and white as I thought. At least I have something to think about. I think you can close this "issue" and you may expect a pull request from me with the advanced sorting in the future. Thanks!

**Comment by netmilk** [comment]
Hi, thanks @ecordell for the response and @RassaLibre for forking Dredd and your contribution and I'm very sorry for the late reaction on my side. 

My opinion is that URL is only an implementation detail or a mean and it has nothing to do with API workflow or design. So general functionality for sorting based on URL space will probably not be implemented or it will not be merged to the upstream Dredd if you file a pull request. I'm sorry about that.

But if you want to make this functionality reusable and available for other users, you can write it as a [`beforeAll`](http://dredd.readthedocs.org/en/latest/hooks/#types-of-hooks) hook function where you have access to an array of [`transction`](http://dredd.readthedocs.org/en/latest/hooks/#transaction-object-structure) obejcts before all transactions are executed. So you can do any magic there and it will be definitely better testable, becouse hooks have stable API, so you won't be forced to deal with stdout etc..

**Comment by RassaLibre** [comment]
Hi, thanks for your answer @netmilk. It seems like I closed the issue exactly in the moment when you commented on it. Thank you for the tip with *beforeAll*, this actually sounds like a good idea! This could actually solve my problem. I am writing a thesis about MDD of REST APIs and I generate API Blueprint file along with the REST API so the user can test it with Dredd. IDs are the only required input from the user and I wanted to make some sort of a work around so even that is automatic. Just to explain. But thank you guys, this discussion was actually very helpful! :)
