### ISSUE TITLE
Modifying the request URI in a dredd hook doesn't work

### ISSUE THREAD

**Issue by jolleon** [apiaryio/dredd#186]
I'm trying to write a dredd *before* hook so that my DELETE action can target the resource that was created by a previous POST.

I've been following [the doc here](https://github.com/apiaryio/dredd/blob/e5e4a5ccab256e2ebde529e8c69b7d1d30294097/docs/hooks.md#sharing-data-between-steps-in-request-stash), but updating `transaction.request.uri` doesn't seem to work (BTW the doc is outdated and refers to `url` while the field seems to be `uri` - I've tried setting both to a different value without success). The updated url does show up on the report that dredd uploads to apiary, but my server is still receiving the old URL.

For the record I'm able to successfully update the request body and headers in a *before* hook, I think the bug is only in the URL/URI.

**Comment by netmilk** [comment]
Hi @jolleon thanks for the report! I'm excited you're using Dredd and the test inspector in Apiary. I'll have a look on it asap.

**Comment by ecordell** [comment]
I think I can help out here - there are a couple of idiosyncrasies with changing the request url. The actual attribute used to construct the request is `fullPath`. This is how I change the url in before hooks:

```javascript
before("Hook Name", (transaction) => {
  transaction.fullPath = "/new/path";
  return transaction.uri = transaction.fullPath;
});
``` 

`transaction.fullPath` sets the path the request will be sent to, and `transaction.request.uri` sets the path that will be recorded in logs and reports. It's a little confusing - I think it would be a good plan to promote "transaction" to an object with getters/setters so that you only need to change one of those properties. 

The above code works for me with the latest dredd version, so if it doesn't work for you you might try upgrading? And you're right - those docs are incorrect. The property has always been `uri`.

**Comment by jolleon** [comment]
Yep this works, thanks! I also found the "uriTemplate" on the transaction object which seems to be a relatively clean way to handle my use case:

    transaction.fullPath = transaction.origin.uriTemplate.replace('{id}', stash['userId']);
    transaction.request.uri = transaction.fullPath

**Comment by netmilk** [comment]
Hi,

tanks a lot, @ecordell for make it clear. Transaction object passed to the function object is very messy at this moment and there is some duplicate data (e.g. `request.uri` and `fullPath`). It's legacy of the evolution and it was never properly designed to be convenient even tough it's a regular API for writing hooks. My goal is to clean it up in some of next releases and make it as convenient as possible. I'll definitely create a proposal, and I'll carefully deprecate old structure. It will throw a deprecation warning  for some time.

@jolleon Please note that one of things I will definitely move somewhere else is that `uriTemplate` key under `origin` against which you're programming. I apologise, but It was very unlucky decision to merge this change adding `uriTemplate` under the `origin` key. In the future, there will be probably some `uriData` object where will be available complete `uriParameters` from the blueprint and this `uriTemplate` for more convenient way to modify URI in hooks.

Here is an issue to kick it off #187

**Comment by liront2** [comment]
Hi all

I tried replacing uri in every way described here but it did not help.
I believe the problem is that my swagger has a defult value, so Dredd overrides my hook somehow.
However, if default is not presented, dredd will fail the test cause value is required.

Swagger:

  /accounts/{id}:
    get:
      description: Returns an account data based on a single ID
      operationId: find_account_by_id
      parameters:
        - name: id
          in: path
          description: ID of an account to fetch
          required: true
          type: string
          pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}"
          default: "2eadb261-afa1-5947-bf20-26bb6f5e1df2"

How can I override the default value?

Thanks

**Comment by honzajavorek** [comment]
@liront2 Just for the record, I'll reply under https://github.com/apiaryio/dredd/issues/597 which you filed separately.
