### ISSUE TITLE
Additional keys in bodies should result to warning or error

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#232]
It can be useful to let user know server is sending undocumented data. Any undocumented (additional) keys in bodies should result in the warning.

I'd consider adding `--strict` mode following [the robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) to don't allow additional properties in response bodies at all.

**Comment by efavre** [comment]
Hi,

I agree, this would be very nice to ensure an ever better API vs blueprint match.

**Comment by sixers** [comment]
Hey! Any progress on this?

**Comment by honzajavorek** [comment]
You can now tackle the problem by using several techniques:

- In API Blueprint in the [`+ Attributes`](https://apiblueprint.org/documentation/specification.html#def-attributes-section) section (which is powered by a language called [MSON](https://apiblueprint.org/documentation/mson/specification.html)), you can now use a brand new type attribute `fixed-type`, which doesn't allow additional properties.
- In API Blueprint, you can also [write your own](https://apiblueprint.org/documentation/specification.html#def-schema-section) [JSON Schema](http://json-schema.org/) with [`additionalProperties: false`](https://spacetelescope.github.io/understanding-json-schema/reference/object.html#properties) on the objects. That was always possible, BTW.
- In Swagger, you specify your data structures as JSON Schema, thus just use the power of the language and specify [`additionalProperties: false`](https://spacetelescope.github.io/understanding-json-schema/reference/object.html#properties) on your objects.

All these options should work with current Dredd versions. Please report under this issue if you find any obstacles when trying to get it working.

I'd say by introducing `fixed-type` to the mix, the problem is sufficiently addressed and this issue could be closed, but I'd like to hear back from all of you involved. Also, I think something like what I just wrote should be in the docs, so I'm turning this into a docs issue.
