### ISSUE TITLE
application/xml media type support

### ISSUE THREAD

**Issue by marlandy** [apiaryio/dredd#234]
I'm trying dredd with my <a href="https://github.com/marlandy/rest-idempotency/blob/master/src/main/webapp/API_DOCUMENTATION.md" target="_blank">REST API documentation</a> and is really useful. However, it works fine when media type is application/json but it doesn't work with **application/xml**. Do you keep in mind to support application/xml in the future?

**Comment by netmilk** [comment]
Hi @marlandy, thank you very much for raising this issue! I would totally love to have support for `application/xml` mediatype in Dredd and [Gavel validator](https://github.com/apiaryio/gavel.js) respectively. Definitely +1

**Comment by honzajavorek** [comment]
@netmilk Making Dredd extensible as described in https://github.com/apiaryio/dredd/issues/253 would allow others to implement this themselves. Hm? :wink:

**Comment by netmilk** [comment]
@marlandy @honzajavorek I quickly drafted some possible workaround solution [here](https://github.com/apiaryio/dredd/issues/253#issuecomment-199298299)

**Comment by honzajavorek** [comment]
This feature request got minimal traction since its creation. It seems majority of Dredd users is okay with Dredd validating just JSON and plain text out of the box. To keep Dredd's core scope maintainable, I suggest this should be supported as something users can implement themselves using hooks, and not as an integral part of Dredd and [Gavel](https://github.com/apiaryio/gavel.js) (even though, if someone made a PR with this to Gavel, I'd be happy to accept it).

XML validation, or custom validation of any kind, can already be implemented using hooks - see https://github.com/apiaryio/dredd/issues/253#issuecomment-258203400 Hopefully that gets better documented one day, but the important thing is that it's possible, so this can be closed now.
