### ISSUE TITLE
Add commandline option for adding/overwriting query parameters

### ISSUE THREAD

**Issue by neonichu** [apiaryio/dredd#251]
Dredd already has the option `—header` for adding/overwriting HTTP headers. It would be nice to have the same functionality for query parameters.

I would make a PR for it, but wanted to first check if that's something you'd consider suitable for merging.

**Comment by honzajavorek** [comment]
Now that Dredd supports [hooks](https://dredd.readthedocs.io/en/latest/hooks/), wouldn't adding parameters using hooks solve this issue?

**Comment by honzajavorek** [comment]
This is possible using hooks and I'm generally opposed to bloating the number of CLI options supported if other, more systematic solutions exist (perhaps `--header` can get deprecated now?).

I can see that both header and query parameters can be used for setting auth and having an option to add auth without all the hooks hassle is tempting, but this issue didn't get much traction since 2015, so I guess nobody's missing it _that_ much.
