### ISSUE TITLE
Switch TCP server with HTTP one

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/dredd#327]
Currently in order to write hooks for a different language, you have to spin un a TCP server, deal with reading from the socket, wait for a `\n` character in order to complete the message and so on.

I think would be definitely easier to move the thing on Http level; it will lower the barrier to write hooks in other languages. Http server with some routes is builtin in most of current programming languages.

This would also enable in a much easier way to have remote webhooks once dredd will be a cloud service as well (if any plan for that)

**Comment by netmilk** [comment]
@XVincentX I think it's generally a good idea! TCP server was used intentionally because of a need of duplex, real-time, synchronous communication. I was considering HTTP, but it would need two HTTP servers. One, in the hook handler for submitting transactions and one in Dredd for accepting transactions after hook execution.

**Comment by XVincentX** [comment]
I agree that it may look like a bit tricky, but I think that there are more benefits than disadvantages.

1. Easier for developer to write hooks - http libraries are everywhere, and stop to use home made delimiters and so on
2. Super easy to make dredd hooks work in the cloud
3. Apiary documentable (that's a feature)

**Comment by netmilk** [comment]
The idea of testing Dredd with Dredd sounds 👌. But it's a lot of work and we don't control all of the hook handler repositories, so coordinating the migration to a different API is something that we should consider as well.

**Comment by XVincentX** [comment]
In my opinion TCP server should be left there forever for legacy reasons. Given that, me may try to move forward.

**Comment by ddelnano** [comment]
@netmilk I can't speak for the Go hooks but if this was implemented I would update the php hooks for the new functionality.

**Comment by XVincentX** [comment]
@ddelnano Good to know - I had this idea while working on [dotnet ones](https://github.com/XVincentX/dredd-hooks-dotnet)

**Comment by netmilk** [comment]
@XVincentX 

> working on dotnet ones

😻🎉👍💯🔝

**Comment by honzajavorek** [comment]
I don't know how the communication of hooks and Dredd is done exactly, but from @XVincentX's comment I believe the architecture is TCP as *transport protocol* and something custom as *application protocol*.

@XVincentX asks for HTTP, which is *application protocol* (running on top of TCP), but isn't fully duplex. While I like HTTP, I think we should use the right tool for particular problem. Can't we find a different, at least somewhat standardized *application protocol*, which we could use in Dredd instead of the custom one? Something which works on top of TCP socket, which allows us full duplex and at the same time it is popular enough that there exist libraries which can simplify the heavy lifting?

I'm not expert on existing, popular TCP-compatible protocols, but wouldn't e.g. [WebSockets](https://en.wikipedia.org/wiki/WebSocket) fit here better than HTTP?

> WebSocket is designed to be implemented in web browsers and web servers, but it can be used by any client or server application. The WebSocket Protocol is an independent TCP-based protocol. Its only relationship to HTTP is that its handshake is interpreted by HTTP servers as an Upgrade request.

**Comment by w-vi** [comment]
Sorry guys, but sending newline delimited messasges using TCP sockets is a basic skill, nothing fancy, pick any tutorial on TCP and you will have the code there. You don't need any library, because it is bultin everywhere, where you get at least some networking. And this is not the famous NIH syndrome, it's like asking for a library to write a simple text to console. Am I so old that I think this is a basic school stuff but kids don't know about it?

**Comment by w-vi** [comment]
I see some benefits in the HTTP, but it's not ease of use, it is the ability to have hooks running in cloud but otherwise I don't see any benefit really.

**Comment by honzajavorek** [comment]
I think we can close this. Sockets work well and HTTP isn't duplex, which is one of the requirements. No other thoughts shared for a year long period.
