### ISSUE TITLE
Add NPM shrinkwrap / clingwrap

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#333]
Start using NPM's shrinkwrap (`shrinkwrap.json`) to freeze entire dependency tree to prevent flaky tests and behavior caused by version bumps in dependencies of dependencies.

**Comment by Almad** [comment]
In the current state of things, I'd recommend using [clingwrap](https://github.com/goodeggs/clingwrap) instead

**Comment by netmilk** [comment]
@Almad Thanks a lot for this!

**Comment by honzajavorek** [comment]
This is not possible for a package installed from NPM. We could do this for local development, but I don't see much value in it. If spending time to something, in this regard, let's spend it on #422.

Also, I'm not sure we suffer many problems caused by version bumps etc. at the moment. We have to monitor (David DM, Snyk), be consistent, be prompt and careful with upgrading. I don't see other ways around it.
