### ISSUE TITLE
Idea: Ability to specify language version used for running hooks

### ISSUE THREAD

**Issue by romansklenar** [apiaryio/dredd#337]
**Question:**
Can I specify language version used for running dredd hooks?

**Use case:**
I have a server where due to compatibility reasons python 2.x is set as default but API app is using python 3.x. In hooks I need to import models to pre-populate database with fixtures for dredd testing so hooks must use the same version of python as tested API app.

Python is specific due to presence of versioned binaries (`python`, `python2`, `python3`, `python3.5`).
But in Ruby projects its also common to have multiple versions installed on system and use version managers (rvm, rbenv) to specify correct ruby version for project using `.ruby-version` files.

**Comment by honzajavorek** [comment]
I'm sorry to get back to this after such a long time. If provided with `--language=python`, Dredd looks for `dredd-hooks-python` executable, the same way `which dredd-hooks-python` works in *NIX command line (or `where dredd-hooks-python` on Windows).

If you, e.g. on macOS, install Python 3 using `brew install python`, then you can install the hooks handler globally as `pip3 install dredd-hooks-python` and the `dredd-hooks-python` executable will be available system-wide, with the correct version of Python. In that case you can just use `--language=python` with Dredd and it should be fine.

If you are using virtualenv, it should still be fine as far as you have it activated. Inside virtualenv, Dredd should be able to see `dredd-hooks-python` when looking for executables using the system path.

Otherwise, you can specify the hooks handler command explicitly: `--language=./venv/bin/dredd-hooks-python` This should work just fine.
