### ISSUE TITLE
Dredd should not use protagonist at all

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/dredd#503]
It currently has protagonist as development dependency

**Comment by honzajavorek** [comment]
It's there just because of [this test](https://github.com/apiaryio/dredd/blob/0b1721a889eb420b39b7ec68dbaf46b808f5b574/test/unit/blueprint-utils-test.coffee). I think the test could use Fury. Willing to contribute? :stuck_out_tongue_winking_eye:

**Comment by argos83** [comment]
I'd love to have the protagonist dependency removed. I know it can be skipped when installing dredd with `--no-optional`. However there's no way to specify that from package.json (see https://github.com/npm/npm/issues/14185). My builds take much longer because of compilation. 

And currently in my local dev env with node 10, the compilation fails with:

```
../src/parse_async.cc:128:14: error: no matching constructor for initialization of 'v8::TryCatch'
    TryCatch try_catch;
```
So every time I try to install any node module (not just dredd), npm tries to re-compile protagonist over and over again.

**Comment by honzajavorek** [comment]
@argos83 I'm sorry, this issue is about something slightly different. Previously, Dredd was using `protagonist` as a way to parse API Blueprint. This has changed with introducing `Fury.js` to the codebase, which encapsulates all parsing, for both API Blueprint and OpenAPI 2. This issue reminds us there's still one place left in the tests where Dredd depends on `protagonist` directly, which shouldn't be.

Actually, it is interesting you found the `dredd > gavel > curl-trace-parser > api-blueprint-http-formatter > protagonist` dependency path, I was not aware of that one. And it's strange, because installing Dredd with `--no-optional` does avoid any compilation, even though according to this dependency path it should still compile `protagonist` as a dependency of the `api-blueprint-http-formatter` 🤔 

Anyway, what you want is to avoid `protagonist` as a dependency completely to avoid parsing. That is not possible as of now. Currently it works as opt-out. A solution would be to help the @apiaryio/adt to finalize https://github.com/apiaryio/drafter-npm/pull/16, which installs `drafter.js` as default and makes the `protagonist` an opt-in. See also [Why Is the Installation So Slow?](https://dredd.readthedocs.io/en/latest/installation.html#why-is-the-installation-so-slow) and [Compiled vs pure JavaScript](https://dredd.readthedocs.io/en/latest/contributing.html#compiled-vs-pure-javascript).

There are no nice workarounds. You need to always run `npm` with `--no-optional` (I'd try to check whether it cannot be specified in `.npmrc` in the root of the project). Another way to hack this, in case you do not need to compile anything else in your dependencies, is to tell npm to use Python 3 for `node-gyp`. This can be done by directing the `--python` npm option or `python` option in the `.npmrc` to a Python 3 binary. Python 3 is not supported by `node-gyp`, so the compilation fails, but right in the beginning, which could shorten your suffering until Drafter supports Node 10.

**Comment by argos83** [comment]
Thanks @honzajavorek for the detailed answer and suggestions. I'll take a look at **adt** to see if I can help with that PR

**Comment by stukker01** [comment]
> Actually, it is interesting you found the `dredd > gavel > curl-trace-parser > api-blueprint-http-formatter > protagonist` dependency path, I was not aware of that one. And it's strange, because installing Dredd with `--no-optional` does avoid any compilation, even though according to this dependency path it should still compile `protagonist` as a dependency of the `api-blueprint-http-formatter` 🤔

@honzajavorek `protagonist` is actually a devDependency of `api-blueprint-http-formatter`, so I think this is why `protagonist` doesn't get installed as a subdependency. Btw as @argos83 mentioned there is a `dredd > drafter > protagonist` path as well, but `protagonist` is also an optional dependency of `drafter`. (However it only turns out from drafter's `package.json`.)

**Comment by jbunton-atlassian** [comment]
My workaround for this is a bit dodgy, but may be of interest to others. I removed `dredd` from my `devDependencies` and added this to the `scripts` in `package.json`:

```
    "postinstall": "npm install --no-save --no-audit --no-optional dredd@^5",
```
