### ISSUE TITLE
Updating from 0.6 to latest version seems to have lost transaction.origin.uriTemplate

### ISSUE THREAD

**Issue by yarandoo** [apiaryio/dredd#618]
Updating from 0.6 to 1.6.1 seems to have lost transaction.origin.**uriTemplate**.

Is the **URITemplate** available under other structure or it has been removed completely?

It was very useful to do things like:

transaction.fullPath = transaction.origin.uriTemplate.replace('{id}', tvSeries.tvSeries.id);

Thanks

**Comment by honzajavorek** [comment]
Hi @yarandoo, that is correct. URI Template was never meant to be part of the `origin` object and was intentionally undocumented in all resources:

- [Transaction Object structure in Dredd docs](http://dredd.readthedocs.io/en/latest/hooks/#transaction-object-structure)
- [blueprint-transactions README](https://github.com/apiaryio/blueprint-transactions) (superseded by [dredd-transactions README](https://github.com/apiaryio/dredd-transactions))

When moving Dredd towards [API Elements](http://api-elements.readthedocs.org/) and Swagger support, we removed the property, since from the very beginning, it was considered rather a pollution of the public interface than a part of the contract. For that reason, there was also no major version bump.

To change the URL, you have to change both `transaction.request.uri` and `transaction.fullPath`:

```js
var hooks = require('hooks');

hooks.beforeEach(function (transaction, done) {
  var id = '123456';

  transaction.request.uri = transaction.request.uri.replace('42', id);
  transaction.fullPath = transaction.fullPath.replace('42', id);

  done();
});
```
