### ISSUE TITLE
Does Dredd have an opinion on the future of Coffeescript?

### ISSUE THREAD

**Issue by greghuc** [apiaryio/dredd#624]
Hi there,

A quick heads up that there's a pretty active discussion going on over at [coffeescript6/discuss](https://github.com/coffeescript6/discuss) about possible next steps for Coffeescript.

Thought you might want to comment, given Dredd is a heavy Coffeescript user. Discussed issues are [here](https://github.com/coffeescript6/discuss/issues).

There's also a survey that's relevant to you: [Survey for devs/teams with maintained Coffescript codebases: happy with CS, or considering migrating?](https://github.com/coffeescript6/discuss/issues/32)

**Comment by honzajavorek** [comment]
Hi @greghuc, [Apiary](https://apiary.io/), Dredd included, is indeed heavy CoffeeScript user, however mainly for historical reasons. Once JavaScript started to evolve again, we decided to write new projects in ES2015. We keep CoffeeScript codebases, but mainly because of the fact that it's hard to migrate them. We don't see the benefit in using CoffeeScript just as a syntax sugar.

I'll consider "voting" in the survey you posted. Thanks for bringing this up! It helped me to realise that it might not be that hard to [decaf](https://github.com/decaffeinate/decaffeinate) at least [Dredd Transactions](https://github.com/apiaryio/dredd-transactions).

**Comment by greghuc** [comment]
@honzajavorek thanks for the response. It would be great if you could express an opinion at the [survey](https://github.com/coffeescript6/discuss/issues/32). It shouldn't take long: 4 questions in  a tiny markdown template. It's not "official", it's just a way of getting feedback about Coffeescript from devs/teams that are currently using it (and maybe changing to ES2015). Opinions gathered will be taken into consideration when considered the future of Coffeescript.

**Comment by honzajavorek** [comment]
@greghuc Okay! Posted in the Survey.

**Comment by greghuc** [comment]
Thanks for taking the time :-)
