### ISSUE TITLE
Adding apiary api key to dredd

### ISSUE THREAD

**Issue by resistdesign** [apiaryio/dredd#682]
I get an error:

```
dredd/node_modules/debug/debug.js:126
  debug.color = selectColor(namespae);
```

**Comment by honzajavorek** [comment]
@resistdesign Thank you for the report, but it's a bit minimalistic and I'm afraid we won't be able to find the problem like this. Could you please provide following information?

- What is your OS? What is your terminal?
- What command did you run and what exact output did it print?
- What is in your `dredd.yml`?
- What's your `dredd --version` output?

Thanks!

**Comment by resistdesign** [comment]
@honzajavorek 

The issue seems obvious: `namespae` has no `c`. But here is what I have:

- What is your OS? macOS Sierra 10.12.1
- What is your terminal? OS X Terminal/bash
- What command did you run and what exact output did it print? 
  - input: `dredd init -r apiary -j apiaryApiKey:********** -j apiaryApiName:*********`
    - `*` = redacted
  - I will not supply further output.
- What is in your dredd.yml? **I don't know what this is.**
- What's your dredd --version output? `dredd v2.2.5 (Darwin 16.1.0; x64)`

**Comment by resistdesign** [comment]
I uninstalled and reinstalled `dredd` and now everything works fine. No idea what the issue was.

**Comment by honzajavorek** [comment]
@resistdesign Thanks for the details, similarly to author of that line, I overlooked the missing `c`. It looks like a bug in the `debug` library, which seems to be a dependency of a Dredd's dependency. Since that dependency probably has benevolent range of accepted versions for `debug`, the problem also sneaked into Dredd. It seems they fixed it in https://github.com/visionmedia/debug/pull/356/, two days ago and released new patch versions, so the same way the problem came, it also went away.

**Comment by resistdesign** [comment]
@honzajavorek LOL, ain't that how it is! :P
