### ISSUE TITLE
Transaction ids are not unique and do not include expected status code

### ISSUE THREAD

**Issue by antkazam** [apiaryio/dredd#866]
## Rationale
Execution of transactions is based on method, URI and status code, however, transaction ID for reporting is only comprised of method and URI. This obscures the behavior of Dredd and makes it harder for me to drive adoption to my teams.

So I'd like to add status code to the transaction ID (`<method> <URI>` becomes `<method> (<status>) <URI>`)

## Current behavior 
```

info: Successfully connected to hooks handler. Waiting 0.1s to start testing.
pass: POST /channelmapper/v1/channel duration: 25ms
skip: POST /channelmapper/v1/channel
skip: POST /channelmapper/v1/channel
pass: GET /v1/channel/9cd4342be duration: 25ms
skip: GET /v1/channel/9cd4342be
pass: GET /v1/channel/9cd4342be duration: 16ms

complete: 3 passing, 0 failing, 0 errors, 3 skipped, 6 total

```

Notice the test status code is not present. 

## Proposed:

```
info: Successfully connected to hooks handler. Waiting 0.1s to start testing.
pass: POST (204) /channelmapper/v1/channel duration: 25ms
skip: POST (401) /channelmapper/v1/channel
skip: POST (404) /channelmapper/v1/channel
pass: GET (200) /v1/channel/9cd4342be duration: 25ms
skip: GET (401) /v1/channel/9cd4342be
pass: GET (404) /v1/channel/9cd4342be duration: 16ms

complete: 3 passing, 0 failing, 0 errors, 3 skipped, 6 total

```

**Comment by honzajavorek** [comment]
Hi, you are right! 🙌  The output doesn't help much. It's because the code for the reporting is there since the beginnings of Dredd and it did not catch up yet on many new features Dredd has.

We have a proposal on how to revamp the output completely - #765. It would be awesome if you take a peek and drop your ideas there as well. I think what you propose here is a small change we can definitely do to improve the current situation 👍
