### ISSUE TITLE
Add watch script for auto recompile of Coffeescript

### ISSUE THREAD

**Issue by antkazam** [apiaryio/dredd#867]
While hacking on Dredd I like to have a watch command auto-recompiling my Coffeescript into JS

I propose adding `npm run watch` which basically does a build (`coffee ...`) with the `-w` flag.

**Comment by honzajavorek** [comment]
Thanks for the suggestion! Ideally, we wouldn't need this at all - see #705. However, if it helps you to hack on Dredd, then whatever works 👍 I tried it out and I think the command you want is

```
coffee -b -w -o lib/ src/
```

Usually, it's possible to add extra params to npm scripts, like this:

```
npm run test -- -b
```

That would run underlying mocha with the `-b` parameter. However, this isn't possible in this case, since we need to change the parameters. Adding doesn't work, I tried. So the only solution to this would be adding an extra script. I suggest `build:watch` to keep it in line with the other names, it would be a special version of the `build` command. What do you think?
