### ISSUE TITLE
dredd is ignoring default value for enum type parameter and failing validation

### ISSUE THREAD

**Issue by karpilin** [apiaryio/dredd#872]
#### Describe your problem

Dredd is failing API Blueprint validation if there is an enum type parameter on the endpoint. Default value is ignored. Apiary validation is working fine.

for example:
```
# Group Example
## Endpoint [GET /example{?type}]

+ Parameters
    + type: `foo` (enum[string], optional)
        + Members
            + `foo`
            + `bar`

+ Response 200 (application/json)
    + Attributes
        + data: `some string` (string, required)
```

throwing out the following error:
```
error: Compilation error in file 'example.apib': URI parameter 'type' example value is not one of enum values. (Example > Endpoint > Endpoint)
```

#### What's your `dredd --version` output?

```
dredd v4.3.0 (Darwin 16.7.0; x64)
```

**Comment by honzajavorek** [comment]
Hi @karpilin! Thanks for the report. This looks like a bug. Is this something what worked in previous Dredd versions?

**Comment by karpilin** [comment]
I think it did, but then I tried to rollback to previous versions all the way to 4.1.0, and dredd-transactions down to 4.2.0. but still was getting this error. 

So the tests, that I believe were previously working, are failing now.

**Comment by honzajavorek** [comment]
Thanks! I'll look into it.

**Comment by honzajavorek** [comment]
I was able to reproduce this. Working on tests and fixes in https://github.com/apiaryio/dredd-transactions/pull/98.

**Comment by iamharish** [comment]
@honzajavorek I'm using v.3.4.5 and started seeing those issues. These tests were working earlier but started failing after I did an `npm install` while trying to fix some other issue. Surprised to see an old version getting affected by a recent change. Is there a version we can use while the fix is getting ready?

**Comment by mousavian** [comment]
We're affected by this as well.

Seems [fury-adapter-swagger](https://github.com/apiaryio/fury-adapter-swagger) has introduced a [breaking change](https://github.com/apiaryio/fury-adapter-swagger/blob/master/CHANGELOG.md#breaking) while bumping version from `0.12.1` to `0.13.0`, then it propagate with https://github.com/apiaryio/dredd-transactions/commit/ea91dc6ebb758ddae1efd2a66b85a879a4b80aa6 PR which i guess is wrongly bumped with a patch version only (from `4.3.0` to `4.3.1`) 
 and since it satisfies the semversion [specified in package.json](https://github.com/apiaryio/dredd/blob/master/package.json#L39)
 hence all new dredd installations, even with restrict version are affected.

**Comment by honzajavorek** [comment]
I'm sorry for the regression. https://github.com/apiaryio/dredd-transactions/pull/98 should soon fix the problem and since it's going to result in another patch version, the fix should automatically spread the same way as the problem did.

**Comment by mousavian** [comment]
Cool @honzajavorek , thanks.
