### ISSUE TITLE
Custom parameters for endpoints require hooks?

### ISSUE THREAD

**Issue by lcofre** [apiaryio/dredd#877]
Hi! Thanks for this project!

I would like to confirm an assumption in case I understood the tool wrong

Dredd tests my API based on my swagger definition, specifically using the default and example values in swagger for the parameters defined, query, path or body parameters. So if I want to include different values or test an endpoint several times I have to write hooks, that look like the one in the examples:

http://dredd.readthedocs.io/en/latest/hooks-nodejs.html#adding-or-changing-uri-query-parameters-to-all-requests
```
var hooks = require('hooks');

hooks.beforeEach(function (transaction) {
  // add query parameter to each transaction here
  var paramToAdd = "api-key=23456"
  if(transaction.fullPath.indexOf('?') > -1){
    transaction.fullPath += "&" + paramToAdd;
  } else{
    transaction.fullPath += "?" + paramToAdd;
  }
});
```

Am I right?

Thanks for your kind help!

**Comment by michalholasek** [comment]
Hello lcofre,

Thank you for using `Dredd`!

You are correct, but you probably want use `before` ([per transaction](http://dredd.readthedocs.io/en/latest/hooks-nodejs.html#modifying-transaction-request-body-prior-to-execution)) instead of `beforeEach` (all transactions) for your use case.

Should you have any more questions, feel free to ask.
