### ISSUE TITLE
Required field in body sometimes missing by the same doc

### ISSUE THREAD

**Issue by pingle1202** [apiaryio/dredd#932]
#### Describe your problem
When I use swagger.yaml to test my mock server, the test result are not always as expected by the same swagger.yaml.

According to my observation, when the result failed, some required request fields are missing in the body tag. 

#### What command line options do you use?

```
$ dredd swagger.yaml http://localhost:4000
```

#### What is in your `dredd.yml`?

```yaml
no
```

#### What's your `dredd --version` output?

```
dredd v4.8.0 (Darwin 17.2.0; x64)
```

**Comment by honzajavorek** [comment]
Hi, sorry for the late response, vacations stepped in. Could you please share your swagger.yml and point out the problematic parts? Thanks!

**Comment by pingle1202** [comment]
[swagger.txt](https://github.com/apiaryio/dredd/files/1550783/swagger.txt)
Please check the swagger.txt

The problematic part as below, when I use dredd command to test my mock server, the request body somtimes missing the required field AdditionalTransInfo.

                required:
                  - ActionSerial
                  - AdditionalTransInfo

**Comment by honzajavorek** [comment]
I suspect this could be caused by the behavior of the [swagger adapter](https://github.com/apiaryio/fury-adapter-swagger). It generates body examples in a way it randomly omits properties which are not required etc.

However, looking at the Swagger file you provided I'm not able to figure out why the adapter should decide to omit the AdditionalTransInfo part in this case. This needs more investigation by either me or @kylef.

**Comment by kylef** [comment]
https://github.com/apiaryio/dredd-transactions/pull/149 will make it so that optional properties are always present in the request/response bodies which should solve the problem here.

**Comment by honzajavorek** [comment]
I believe this should be solved. Please report in a new issue or comment under this one if you're still experiencing the problem.
